import math
import networkx as nx
import plotly.graph_objs as go
import pylab
import plant_gravitropism as pg

def get_observed_lateral_segments(arbor):
    """
    Trace all lateral roots from tip to main root.
    Nodes are tuples (x, y).
    """
    segments = []
    tips = [n for n in arbor.nodes if arbor.nodes[n]["label"] == "lateral root tip"]

    for tip in tips:
        curr = tip
        prev = None
        while True:
            neighbors = list(arbor.neighbors(curr))
            if prev is not None:
                neighbors = [n for n in neighbors if n != prev]

            if len(neighbors) == 0:
                break  # end of lateral root

            next_node = neighbors[0]
            segments.append((curr, next_node))
            prev, curr = curr, next_node

            if arbor.nodes[curr]["label"].startswith("main root"):
                break

    return segments

def get_line_segment_drawings(line_segments, color="gray"):
    """Convert line segments into Plotly Scatter objects."""
    traces = []
    for seg in line_segments.values():
        (x0, y0), (x1, y1) = seg  # node IDs are tuples
        traces.append(go.Scatter(
            x=[x0, x1], y=[y0, y1],
            mode="lines",
            line=dict(color=color, width=4),
            showlegend=False
        ))
    return traces

def get_lateral_segment_drawings(lateral_segments, color="lightgray"):
    traces = []
    for seg in lateral_segments:
        (x0, y0), (x1, y1) = seg
        traces.append(go.Scatter(
            x=[x0, x1], y=[y0, y1],
            mode="lines",
            line=dict(color=color, width=2),
            showlegend=False
        ))
    return traces

def get_tip_drawings(lat_tips, color="orange"):
    return [go.Scatter(x=[tip[0]], y=[tip[1]],
                       mode="markers",
                       marker=dict(color=color),
                       showlegend=False)
            for tip in lat_tips]

def get_opt_to_pq_drawings(G, final, color="blue"):
    drawings = []
    for result in final:
        x0, y0 = result[4], result[5]
        p, q = result[6], result[7]
        if G == 0:
            x_coords, y_coords = [p, x0], [q, y0]
        else:
            b, c = pg.calc_coeff(G, x0, y0, p, q)
            x_coords = pylab.linspace(min(p, x0), max(p, x0))
            y_coords = G * x_coords**2 + b*x_coords + c
        drawings.append(go.Scatter(
            x=x_coords, y=y_coords,
            mode="lines",
            line=dict(color=color),
            showlegend=False
        ))
    return drawings

def get_insertion_point_drawings(insertion_points, color="blue"):
    """
    Draw lateral root insertion points (where a lateral meets the main root)
    as blue markers the same size as the lateral root tip markers.

    (generated by Claude)
    """
    return [go.Scatter(
                x=[pt[0]], y=[pt[1]],
                mode="markers",
                marker=dict(color=color, size=8),
                showlegend=False)
            for pt in insertion_points]

def get_lateral_nodes(lateral_segments):
    """
    Collect every unique node that appears anywhere along the lateral root
    segments — both endpoints of every segment.
 
    This covers all intermediate nodes along each lateral (the nodes between
    the tip and the insertion point), as well as the tips and insertion points
    themselves. Duplicates are removed so overlapping segment endpoints are
    not drawn twice.

    (generated by Claude)
    """
    nodes = set()
    for node_a, node_b in lateral_segments:
        nodes.add(node_a)
        nodes.add(node_b)
    return list(nodes)

def get_lateral_node_drawings(lateral_nodes, color="white"):
    """
    Draw every node along the lateral root segments as a default-sized marker.
    No explicit size is passed so Plotly uses its own default (6px).

    (generated by Claude)
    """
    return [go.Scatter(
                x=[node[0]], y=[node[1]],
                mode="markers",
                marker=dict(color=color),
                showlegend=False)
            for node in lateral_nodes]


def create_graphs(arbor, G, alpha):
    """
        Changed slightly for toy network
    """
    return arbor

def plot_arbors(arbor, G, alpha, show_observed=True, paper=False, save_fname=None):
    arbor_name = arbor.graph.get('arbor name', 'toy arbor')

    wiring, delay, total_orthogonal, total_sq_orthogonal = evaluate_parameters(arbor, G, alpha)

    print(f"\n→ G = {G}, alpha = {alpha}")
    print(f"Wiring cost: {wiring:.4f}")
    print(f"Conduction delay: {delay:.4f}\n")
    print(f"Total orthogonal distance: {total_orthogonal:.4f}")
    print(f"Total squared orthogonal distance: {total_sq_orthogonal:.4f}\n")

    fig = go.Figure()

    if show_observed:
        main_segments = get_main_root_segments(arbor)
        # convert list of tuples to dict for get_line_segment_drawings
        main_segments_dict = {i: seg for i, seg in enumerate(main_segments)}
        for trace in get_line_segment_drawings(main_segments_dict, color="black"):
            fig.add_trace(trace)

        lateral_segments = get_observed_lateral_segments(arbor)
        for trace in get_lateral_segment_drawings(lateral_segments, color="green"):
            fig.add_trace(trace)

        # --- all nodes along lateral root segments (white, default size) ---
        lateral_nodes = get_lateral_nodes(lateral_segments)
        for trace in get_lateral_node_drawings(lateral_nodes, color="white"):
            fig.add_trace(trace)

        lat_tips = [n for n in arbor.nodes if arbor.nodes[n]["label"] == "lateral root tip"]
        for trace in get_tip_drawings(lat_tips, color="orange"):
            fig.add_trace(trace)
        
        # --- lateral root insertion points (blue, same size as tips) ---
        insertion_points = get_lateral_insertion_points(lateral_segments, arbor)
        for trace in get_insertion_point_drawings(insertion_points, color="blue"):
            fig.add_trace(trace)

        base_node = arbor.graph['main root base']
        fig.add_trace(go.Scatter(
            x=[base_node[0]], y=[base_node[1]],
            mode="markers",
            marker=dict(color="purple", size=30),
            name="Main root base"
        ))

    fig.update_layout(
        title=f"Arbor: {arbor_name}   |   G={G}, alpha={alpha}",
        annotations=[
            dict(
                text="",
                xref="paper", yref="paper",
                x=0.5, y=-0.1,
                showarrow=False,
                font=dict(size=14)
            )
        ],
        xaxis_title="X",
        yaxis_title="Y",
        yaxis_autorange="reversed",
        width=850,
        height=700,
        margin=dict(t=80, b=80)
    )
    
    if paper:
        fig.update_layout(
            xaxis_title=None,
            yaxis_title=None,
            annotations=[], 
            title_text="", 
            showlegend=False
        )
        fig.update_xaxes(showticklabels=False)
        fig.update_yaxes(showticklabels=False)


    fig.show()
    
    if save_fname != None:
        print("saving fig to " + save_fname)
        fig.write_image(save_fname)