name: plant-architecture
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.3
  - jupyter
  - scipy
  - matplotlib
  - plotly
  - networkx
  - pandas
  - seaborn
  - pingouin
  - sympy
  - statsmodels
  - scikit-bio
  - python-kaleido
  - scikit-posthocs
